# Generated by Django 2.2 on 2020-10-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0002_auto_20201019_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
